title: Betty A. Onyango
logo: https://github.com/Betty-coded/portfolio/blob/main/Profile.jpg?raw=true
author: Betty A. Onyango
description: Welcome to My Portfolio
description_extended: >
  I am an MBA student at University Canada West, with a focus on business strategy and entrepreneurship. With a strong background in client relations and project management, I aim to leverage my academic and professional experiences to deliver impactful solutions.
show_downloads: true

theme: jekyll-theme-minimal
