title: Betty A. Onyango
navbar:
    logo:
      ![Profile](https://github.com/Betty-coded/portfolio/blob/main/Profile.jpg?raw=true)
      
#description: Welcome to My Portfolio
## About Me
I am an MBA student at University Canada West, with a focus on business strategy and entrepreneurship. With a strong background in client relations and project management, I aim to leverage my academic insights to drive innovation and business growth in the tech and digital sectors. I have a passion for leveraging business strategy and digital transformation to solve complex challenges and drive long-term success.
#show_downloads: true
theme: jekyll-theme-minimal
